# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/
title:            'ISCC Oral History'
description:      'A digital archive of photos and an oral history of the Islamic Society of Chester County'
url:              'https://maxjdugan.github.io'
baseurl:          '/iscc'
copyright:        '2021 <a href='mailto:max.j.dugan@gmail.com>Max Johnson Dugan</a>'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  iscc: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'iscc_item' # the layout for the pages to use
    metadata:
      source: 'iscc_metadata.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/iscc_images' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      iscc:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - author
          - location
          - label
          - _date
          - description
          - object_type

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Oral History'
    link: '/exhibits/a/'
  - label: 'Images'
    sub:
      - label: 'Browse'
        link: '/collection/'
      - label: 'Search'
        link: '/search/'
      - label: 'Reuse'
        link: '/reuse/'
  - label: 'About'
    sub:
      - label: 'About '
        link: '/about/'
      - label: 'ISCC'
        link: '/the_iscc/'
      - label: 'Wax'
        link: 'https://minicomp.github.io/wiki/wax/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#



# FIN
